---
server:
  port: 8081
  servlet:
    context-path: /accounts
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    platform: postgres
    url: "jdbc:postgresql://192.168.178.22:5432/account_service_database"
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    properties: ~
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
