---
eureka:
  client:
    service-url:
      defaultZone: "http://192.168.178.22:8761/eureka/"
  instance:
    preferIpAddress: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
logging:
  level:
    org.springframework.security: INFO
