---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    platform: postgres
    url: "jdbc:postgresql://192.168.178.22:5432/deposit_service_database"
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    properties: ~
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  rabbitmq:
    host: rabbitmq
    listener:
      direct:
        default-requeue-rejected: true
        server:
          port: 9999
    password: guest
    port: 5672
    username: guest
